# Generated by Django 4.1.5 on 2024-09-30 01:34

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='number_of_pages',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='rental',
            unique_together={('user', 'book', 'rental_date')},
        ),
        migrations.RemoveField(
            model_name='rental',
            name='return_date',
        ),
    ]
