# Generated by Django 4.1.5 on 2024-09-30 04:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_alter_book_number_of_pages_alter_rental_rental_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rental',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
